import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast';
import './globals.css'
import LayoutMainWrapper from '@/components/LayoutMainWrapper';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chatbot',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </head>
      <body className={`${inter.className} h-screen overflow-x-hidden`}>
        <main className='bg-white h-full '>
          <div>
            <Toaster
              position="top-right"
            />
          </div>
          <LayoutMainWrapper>
            {children}
          </LayoutMainWrapper>
        </main>
      </body>
    </html>
  )
}
